"""
bcc_flatband_oh_irreps.py

Symmetry (Oh group representation) analysis of the 6 flat-band eigenvectors
at lambda=-3 in the periodic BCC 3x3x3 lattice.

The 540 faces split into 27 BCs x 20 faces. The 6 flat bands at lambda=-3
persist across ALL 27 k-points (bandwidth = 0). These modes are null vectors
of all inter-BC hopping matrices T(R!=0) and live entirely within each BC's
20-face internal subspace.

The Oh group (48 elements, center of the BCC cube) acts on the 20 faces.
We decompose the resulting 6D representation into Oh irreducible representations.

Only numpy and scipy are used.
Results written to: d:/AI thoery/.agent/scripts/bcc_flatband_oh_results.txt
"""

import itertools
import sys
from collections import defaultdict

import numpy as np

OUT_PATH = "d:/AI thoery/.agent/scripts/bcc_flatband_oh_results.txt"
_LOG_LINES = []


def log(msg=""):
    """Print to stdout AND buffer for results file."""
    print(msg)
    _LOG_LINES.append(str(msg))


# ============================================================
# Lattice construction (copied verbatim from bcc_bloch_decomposition.py)
# ============================================================

def build_bcc_lattice_periodic():
    body_centers = []
    for i, j, k in itertools.product(range(3), repeat=3):
        body_centers.append((i, j, k))
    return body_centers


def enumerate_simplex_faces(bc_ijk):
    """20 canonical faces for BC at grid position bc_ijk."""
    i, j, k = bc_ijk
    bc_v = ('bc', i, j, k)

    orig_corners = []
    for dx, dy, dz in itertools.product((0, 1), repeat=3):
        ox, oy, oz = i + dx, j + dy, k + dz
        wx, wy, wz = ox % 3, oy % 3, oz % 3
        orig_corners.append(((ox + oy + oz) % 2, ('c', wx, wy, wz)))

    even_corners = [v for (par, v) in orig_corners if par == 0]
    odd_corners  = [v for (par, v) in orig_corners if par == 1]
    assert len(even_corners) == 4 and len(odd_corners) == 4

    faces = []
    for tet_corners in (even_corners, odd_corners):
        simplex_verts = [bc_v] + tet_corners
        for combo in itertools.combinations(simplex_verts, 3):
            faces.append(frozenset(combo))

    assert len(faces) == 20
    return faces


def translate_vertex(v, shift_ijk):
    si, sj, sk = shift_ijk
    if v[0] == 'bc':
        _, i, j, k = v
        return ('bc', (i + si) % 3, (j + sj) % 3, (k + sk) % 3)
    else:
        _, cx, cy, cz = v
        return ('c', (cx + si) % 3, (cy + sj) % 3, (cz + sk) % 3)


def translate_face(face, shift_ijk):
    return frozenset(translate_vertex(v, shift_ijk) for v in face)


def build_all_faces(body_centers):
    ref_bc = (0, 0, 0)
    ref_faces = enumerate_simplex_faces(ref_bc)

    face_to_idx = {}
    bc_face_indices = []

    global_idx = 0
    for bc_idx, bc_ijk in enumerate(body_centers):
        local_indices = []
        for m, ref_face in enumerate(ref_faces):
            shifted_face = translate_face(ref_face, bc_ijk)
            if shifted_face not in face_to_idx:
                face_to_idx[shifted_face] = global_idx
                global_idx += 1
            local_indices.append(face_to_idx[shifted_face])
        bc_face_indices.append(local_indices)

    return face_to_idx, bc_face_indices, ref_faces


def build_adjacency_matrix(face_to_idx):
    N = len(face_to_idx)
    A = np.zeros((N, N), dtype=float)

    all_faces_sets = [None] * N
    for face, idx in face_to_idx.items():
        all_faces_sets[idx] = face

    vertex_to_faces = defaultdict(set)
    for face, idx in face_to_idx.items():
        for v in face:
            vertex_to_faces[v].add(idx)

    candidate_pairs = set()
    for v, fset in vertex_to_faces.items():
        flist = sorted(fset)
        for a in range(len(flist)):
            for b in range(a + 1, len(flist)):
                candidate_pairs.add((flist[a], flist[b]))

    for i, j in candidate_pairs:
        if len(all_faces_sets[i] & all_faces_sets[j]) == 2:
            A[i, j] = 1.0
            A[j, i] = 1.0

    return A


def bc_flat_index(bc_ijk):
    return bc_ijk[0] * 9 + bc_ijk[1] * 3 + bc_ijk[2]


# ============================================================
# Oh group generation
# ============================================================

def generate_oh_elements():
    """
    Generate all 48 elements of Oh as 3x3 integer matrices.

    Oh = O x {I, -I} where O is the rotation group of the cube (24 elements).
    O is generated by: C4z (90-deg rotation about z) and C3_111 (120-deg about [1,1,1]).

    C4z: (x,y,z) -> (-y, x, z)
    C3_111: (x,y,z) -> (z, x, y)

    We generate O by repeated composition, then add inversion to get Oh.
    """
    # Define generators as 3x3 integer matrices
    C4z = np.array([[0, -1, 0],
                    [1,  0, 0],
                    [0,  0, 1]], dtype=int)

    C3_111 = np.array([[0, 0, 1],
                       [1, 0, 0],
                       [0, 1, 0]], dtype=int)

    # Generate O by BFS/closure
    def mat_to_tuple(m):
        return tuple(m.flatten())

    O_set = {}
    queue = [np.eye(3, dtype=int)]
    O_set[mat_to_tuple(np.eye(3, dtype=int))] = np.eye(3, dtype=int)

    generators = [C4z, C3_111, C4z.T, C3_111.T]  # include inverses for faster closure

    while queue:
        current = queue.pop(0)
        for g in generators:
            new = g @ current
            key = mat_to_tuple(new)
            if key not in O_set:
                O_set[key] = new
                queue.append(new)

    assert len(O_set) == 24, f"Expected 24 rotations, got {len(O_set)}"

    # Add inversion: Oh = O union (-I)*O
    inv = -np.eye(3, dtype=int)
    Oh_elements = []
    for key, mat in O_set.items():
        Oh_elements.append(mat.copy())
        Oh_elements.append((inv @ mat).copy())

    assert len(Oh_elements) == 48, f"Expected 48 Oh elements, got {len(Oh_elements)}"
    return Oh_elements


# ============================================================
# Oh conjugacy class classification
# ============================================================

def classify_oh_element(g):
    """
    Classify a 3x3 integer Oh matrix into its conjugacy class.

    Oh conjugacy classes (10 total):
      E    (1):  proper,  trace=3   (identity)
      C3   (8):  proper,  trace=0   (120-deg about body diag)
      C2   (6):  proper,  trace=-1  (180-deg about face diag)
      C4   (6):  proper,  trace=1   (90-deg about face normal)
      C2'  (3):  proper,  trace=-1  (180-deg about face normal -- but wait,
                                      same trace as C2 class)
      i    (1):  improper, trace=-3  (inversion)
      S6   (8):  improper, trace=0   (= i*C3)
      sigma_h(6): improper, trace=1  (reflection through face-normal plane)
      S4   (6):  improper, trace=-1  (= i*C4, but trace -1... let me re-examine)
      sigma_d(3): improper, trace=3  ... no

    Actually the correct classification for Oh uses det and trace:
      Proper (det=+1):
        E:   trace = 3
        C3:  trace = 0   (8 elements, body diagonals ±120, ±240)
        C2:  trace = -1  (6 elements, face-diagonal C2 axes)
        C4:  trace = 1   (6 elements, face-normal C4 axes, ±90 deg)
        C2': trace = -1  (3 elements, face-normal C2 axes, 180 deg)
      Wait -- C2 and C2' both have trace -1; we need another distinguisher.

    For det=+1, trace=-1: 9 elements total.
      C2  (6): rotation by 180 about a face-diagonal axis [1,1,0] type
      C2' (3): rotation by 180 about a face-normal axis [1,0,0] type

    Distinguishing: the axis type.
    C2' axes are {±x, ±y, ±z} (3 axes, 3 rotations by 180).
    C2  axes are {[1,±1,0] type} (6 axes, 6 rotations by 180).

    For det=+1, trace=-1: check if axis is ±e_i (face-normal, C2') or diagonal (C2).
    The rotation axis is the eigenvector with eigenvalue +1.
    For C2': axis is a coordinate axis -> exactly one component of the
             unnormalized eigenvec is nonzero in coord directions.
    Alternative: for a 180-deg rotation R about unit axis n,
      R = 2*n*n^T - I  => trace = 2|n|^2 - 3 = 2-3 = -1 (for unit n). Consistent.
      The eigenvector with eigenvalue +1 is n.

    Simpler: for det=+1, trace=-1 elements:
      C2' (3 elements): the matrix has exactly one +1 on diagonal and two -1s
                        (corresponding to reflection through two coord planes, i.e.,
                         rotation by 180 about a coord axis).
                        BUT: 180-deg rotation about x: diag(1,-1,-1), trace=-1 YES.
                        And: 180-deg rotation about [1,1,0]/sqrt(2):
                          R = [[0,1,0],[1,0,0],[0,0,-1]], trace=-1+0+0... wait trace=0+0-1=-1. Hmm.
                          Actually: R_[1,1,0] = [[0,1,0],[1,0,0],[0,0,-1]]:
                          trace = 0+0+(-1) = -1. Same trace.

    Let me just enumerate: there are 9 proper rotations with trace=-1 in O.
    Among these, 3 are C2' (axes ±x,±y,±z) and 6 are C2 (face-diagonal axes).
    C2' matrix for axis x = diag(1,-1,-1) -- has diagonal entries only.
    C2 matrix for axis [1,1,0]: R[i,j] = 2*n_i*n_j - delta_ij
      n = [1,1,0]/sqrt(2): R = [[0,1,0],[1,0,0],[0,0,-1]]
    C2' always diagonal. So: if det=+1, trace=-1, matrix is diagonal -> C2'.

    Full classification:
      det=+1: trace=3 -> E (1)
              trace=0 -> C3 (8)
              trace=1 -> C4 (6)
              trace=-1, diagonal -> C2' (3)
              trace=-1, not diagonal -> C2 (6)
      det=-1: trace=-3 -> i (1)
              trace=0 -> S6 (8)   [= i * C3]
              trace=-1 -> sigma_h (6)  [= i * C4]
              trace=1, diagonal -> sigma_d (3)  [= i * C2']
              trace=1, not diagonal -> S4 (6)  [= i * C2]

    Wait, let me recheck sigma_d and S4:
      i * C2' (axis x) = diag(-1,-1,-1)*diag(1,-1,-1) = diag(-1,1,1).
        trace = -1+1+1 = 1. diagonal. -> sigma_d.
      i * C2 (axis [1,1,0]) = -R_[1,1,0] = [[0,-1,0],[-1,0,0],[0,0,1]].
        trace = 0+0+1 = 1. not diagonal. -> S4? Let me check:
        S4 = i * C4. C4 (axis z, 90-deg): [[0,-1,0],[1,0,0],[0,0,1]], trace=0+0+1=1.
        i*C4: [[0,1,0],[-1,0,0],[0,0,-1]], trace=0+0-1=-1. That's improper, trace=-1.
        So: det=-1, trace=-1 -> sigma_h (6 elements). Hmm that doesn't match.

    Let me just do it numerically and verify counts.
    """
    det = int(round(np.linalg.det(g)))  # +1 or -1
    tr = int(round(np.trace(g)))

    if det == 1:
        if tr == 3:
            return 'E'
        elif tr == 0:
            return 'C3'
        elif tr == 1:
            return 'C4'
        elif tr == -1:
            # Distinguish C2 vs C2': diagonal matrix?
            off_diag = np.abs(g - np.diag(np.diag(g))).sum()
            if off_diag < 0.5:
                return "C2'"
            else:
                return 'C2'
        elif tr == -3:
            # Only happens if all eigenvalues are -1 and det=+1... impossible for 3x3 real.
            # This shouldn't occur in O.
            return 'UNKNOWN_proper'
        else:
            return f'UNKNOWN_proper_tr{tr}'
    else:  # det == -1
        # Improper elements. Classification:
        #
        # Trace-based (det=-1):
        #   i:       trace = -3
        #   S6:      trace =  0  (= i*C3, order 6)
        #   S4:      trace = -1  (= i*C4, order 4, g^2 is proper C2)
        #   sigma_h: trace =  1, non-diagonal (= i*C2 face-diagonal, 6 elements)
        #   sigma_d: trace =  1, diagonal     (= i*C2' face-normal,  3 elements)
        #
        # Derivation:
        #   C4(z) = [[0,-1,0],[1,0,0],[0,0,1]], trace=1.
        #   i*C4(z) = [[0,1,0],[-1,0,0],[0,0,-1]], trace=-1, det=-1. -> S4.
        #   C2'(x) = diag(1,-1,-1), trace=-1, diagonal.
        #   i*C2'(x) = diag(-1,1,1), trace=1, diagonal. -> sigma_d.
        #   C2([1,1,0]) = [[0,1,0],[1,0,0],[0,0,-1]], trace=-1, non-diagonal.
        #   i*C2([1,1,0]) = [[0,-1,0],[-1,0,0],[0,0,1]], trace=1, non-diagonal. -> sigma_h.
        #
        # Class sizes: S4(6), sigma_h(6), sigma_d(3) -- consistent with char table.
        if tr == -3:
            return 'i'
        elif tr == 0:
            return 'S6'
        elif tr == -1:
            return 'S4'
        elif tr == 1:
            # sigma_h (6 elements, non-diagonal = i*C2) or sigma_d (3 elements, diagonal = i*C2')
            off_diag = np.abs(g - np.diag(np.diag(g))).sum()
            if off_diag < 0.5:
                return 'sigma_d'
            else:
                return 'sigma_h'
        else:
            return f'UNKNOWN_improper_tr{tr}'


def verify_oh_classification(oh_elements):
    """Verify that the 48 elements split into the correct conjugacy class sizes."""
    classes = defaultdict(list)
    for g in oh_elements:
        cls = classify_oh_element(g)
        classes[cls].append(g)

    expected = {
        'E': 1, 'C3': 8, 'C2': 6, 'C4': 6, "C2'": 3,
        'i': 1, 'S6': 8, 'sigma_h': 6, 'S4': 6, 'sigma_d': 3
    }

    log("  Oh element classification:")
    ok = True
    for cls, exp in sorted(expected.items()):
        got = len(classes.get(cls, []))
        status = "OK" if got == exp else f"WRONG (expected {exp})"
        log(f"    {cls:10s}: {got:2d}  {status}")
        if got != exp:
            ok = False

    unknowns = [cls for cls in classes if cls not in expected]
    if unknowns:
        log(f"  UNKNOWN classes: {unknowns}")
        ok = False

    log(f"  Total: {sum(len(v) for v in classes.values())} (expect 48)")
    log(f"  Classification correct? {ok}")
    return classes, ok


# ============================================================
# Oh action on face basis
# ============================================================

def vertex_coordinates(v):
    """
    Return the 'geometric' coordinates of a vertex for Oh action.
    The Oh group is centered at (1.5, 1.5, 1.5) (center of the 3x3x3 cube).
    BC vertices: ('bc', i, j, k) -> (i+0.5, j+0.5, k+0.5) -> centered: (i-1, j-1, k-1)
    Corner vertices: ('c', cx, cy, cz) -> (cx, cy, cz) -> centered: (cx-1.5, cy-1.5, cz-1.5)
    """
    if v[0] == 'bc':
        _, i, j, k = v
        return np.array([i - 1.0, j - 1.0, k - 1.0], dtype=float)
    else:
        _, cx, cy, cz = v
        return np.array([cx - 1.5, cy - 1.5, cz - 1.5], dtype=float)


def apply_oh_to_vertex(g, v):
    """
    Apply Oh element g (3x3 integer matrix, acts on centered coordinates)
    to vertex v, then unwrap back to the lattice representation.

    Returns the transformed vertex (as ('bc',...) or ('c',...) tuple),
    possibly in a different BC cell. We also return which BC cell
    the image would belong to (for the face's BC assignment).
    """
    coord = vertex_coordinates(v)
    new_coord = g @ coord

    if v[0] == 'bc':
        # BC vertex: centered coord = (i-1, j-1, k-1) for i,j,k in {0,1,2}.
        # new_coord should also be in {-1, 0, 1}^3 on the torus.
        # Unwrap: new_coord + 1 = (i',j',k') in {0,1,2} mod 3.
        i_new = int(round(new_coord[0] + 1.0)) % 3
        j_new = int(round(new_coord[1] + 1.0)) % 3
        k_new = int(round(new_coord[2] + 1.0)) % 3
        return ('bc', i_new, j_new, k_new)
    else:
        # Corner vertex: centered coord = (cx-1.5, cy-1.5, cz-1.5).
        # new_coord should be in {-1.5, -0.5, 0.5, 1.5}^3.
        # Unwrap to (cx', cy', cz') in {0,1,2}: cx' = new_coord[0] + 1.5 (mod 3).
        cx_new = int(round(new_coord[0] + 1.5)) % 3
        cy_new = int(round(new_coord[1] + 1.5)) % 3
        cz_new = int(round(new_coord[2] + 1.5)) % 3
        return ('c', cx_new, cy_new, cz_new)


def apply_oh_to_face(g, face):
    """Apply Oh element g to all vertices of a face. Returns transformed face as frozenset."""
    return frozenset(apply_oh_to_vertex(g, v) for v in face)


def which_bc_owns_face(face):
    """
    Determine which BC cell owns this face (by the BC vertex in the face, if any).
    If no BC vertex, infer from corner coordinates.

    For a face from the reference BC(0,0,0)'s 20 faces after Oh rotation:
    the BC vertex in the transformed face tells us which BC it ended up in.
    """
    for v in face:
        if v[0] == 'bc':
            return (v[1], v[2], v[3])
    # No BC vertex: this face is a pure corner face (3 corner vertices).
    # Determine ownership from which simplex it belongs to.
    # This is trickier; we'll handle it after building the face lookup.
    return None


def build_oh_permutation(g, ref_faces, ref_face_to_local_idx, face_to_idx, bc_face_indices, body_centers):
    """
    Build the 20x20 permutation matrix for Oh element g acting on the reference
    BC(0,0,0)'s 20 faces.

    For each reference face f_m (m=0..19):
      1. Apply g to get face g(f_m).
      2. g(f_m) belongs to some BC(i,j,k) in the lattice.
      3. Translate g(f_m) back to BC(0,0,0) by shift -(i,j,k) mod 3.
      4. The translated face must be one of the 20 reference faces -> local index n.
      5. P[n, m] = 1.

    This gives the effective 20x20 action on the internal face space.

    Returns: P (20x20 numpy array, permutation matrix).
    """
    P = np.zeros((20, 20), dtype=float)

    for m, face in enumerate(ref_faces):
        # Apply g
        g_face = apply_oh_to_face(g, face)

        # Find which BC owns this transformed face
        bc_owner = which_bc_owns_face(g_face)

        if bc_owner is None:
            # Pure corner face -- need to find it in face_to_idx and determine BC from there
            # This shouldn't happen for the reference BC faces (each has 1 BC vertex),
            # but handle gracefully.
            if g_face in face_to_idx:
                global_idx = face_to_idx[g_face]
                # Find which BC has this global index
                for bc_idx, bc_ijk in enumerate(body_centers):
                    if global_idx in bc_face_indices[bc_idx]:
                        bc_owner = bc_ijk
                        break
            if bc_owner is None:
                raise ValueError(f"Cannot find BC owner for face {g_face}")

        # Translate back to BC(0,0,0) by applying shift -(bc_owner)
        inv_shift = tuple((-s) % 3 for s in bc_owner)
        translated_face = translate_face(g_face, inv_shift)

        # Look up in reference face set
        if translated_face not in ref_face_to_local_idx:
            raise ValueError(
                f"Translated face {translated_face} not in reference face set.\n"
                f"  g={g}, face={face}, g_face={g_face}, bc_owner={bc_owner}"
            )

        n = ref_face_to_local_idx[translated_face]
        P[n, m] = 1.0

    # Verify it's a permutation matrix
    row_sums = P.sum(axis=1)
    col_sums = P.sum(axis=0)
    assert np.allclose(row_sums, 1.0), f"P not a permutation matrix (row sums: {row_sums})"
    assert np.allclose(col_sums, 1.0), f"P not a permutation matrix (col sums: {col_sums})"

    return P


# ============================================================
# Oh character table
# ============================================================

# Conjugacy class order (sizes):
OH_CLASS_ORDER = {
    'E': 1, 'C3': 8, 'C2': 6, 'C4': 6, "C2'": 3,
    'i': 1, 'S6': 8, 'sigma_h': 6, 'S4': 6, 'sigma_d': 3
}

# Column order for character table:
# Standard Oh char table column order: E, C3, C2, C4, C2', i, S6, sigma_d, S4, sigma_h
# Note: sigma_d (6 elements, non-diagonal mirrors) comes before S4 (6 elements),
#       and sigma_h (3 elements, diagonal mirrors) comes last.
# Our classifier: sigma_h = non-diagonal (6 elems), sigma_d = diagonal (3 elems).
# IMPORTANT: the classifier names are SWAPPED from standard Oh notation:
#   "sigma_h" in our classifier = sigma_d in standard Oh (6 non-diagonal mirrors)
#   "sigma_d" in our classifier = sigma_h in standard Oh (3 diagonal mirrors)
# We keep the classifier as-is and correct the character table column order here.
#
# Standard convention (used in char table):
#   sigma_d = 6 diagonal mirror planes (non-diagonal matrix, i*C2 type)
#   sigma_h = 3 horizontal mirror planes (diagonal matrix, i*C2' type)
#
# In our code, classify_oh_element returns:
#   'sigma_h' for the 6 non-diagonal ones (= standard sigma_d)
#   'sigma_d' for the 3 diagonal ones (= standard sigma_h)
#
# So the column order in the character table must match our classifier labels:
OH_CLASSES = ['E', 'C3', 'C2', 'C4', "C2'", 'i', 'S6', 'sigma_h', 'S4', 'sigma_d']

# Character table columns mapped to our classifier labels:
# E(1), C3(8), C2(6), C4(6), C2'(3), i(1), S6(8),
#   sigma_h=our_code(6)=std_sigma_d, S4(6), sigma_d=our_code(3)=std_sigma_h
#
# Standard Oh char table (Koster notation), standard column order:
# E, C3, C2, C4, C2', i, S6, sigma_d, S4, sigma_h
# A1g: 1,  1,  1,  1,  1,  1,  1,  1,  1,  1
# A2g: 1,  1, -1, -1,  1,  1,  1, -1, -1,  1
# Eg:  2, -1,  0,  0,  2,  2, -1,  0,  0,  2
# T1g: 3,  0, -1,  1, -1,  3,  0, -1,  1, -1
# T2g: 3,  0,  1, -1, -1,  3,  0,  1, -1, -1
# A1u: 1,  1,  1,  1,  1, -1, -1, -1, -1, -1
# A2u: 1,  1, -1, -1,  1, -1, -1,  1,  1, -1
# Eu:  2, -1,  0,  0,  2, -2,  1,  0,  0, -2
# T1u: 3,  0, -1,  1, -1, -3,  0,  1, -1,  1
# T2u: 3,  0,  1, -1, -1, -3,  0, -1,  1,  1
#
# Reordering columns 8 and 10 (sigma_d<->sigma_h in standard -> our sigma_h, sigma_d):
# New order: E, C3, C2, C4, C2', i, S6, our_sigma_h(=std_sigma_d), S4, our_sigma_d(=std_sigma_h)
OH_CHAR_TABLE = {
    'A1g': [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
    'A2g': [ 1,  1, -1, -1,  1,  1,  1, -1, -1,  1],
    'Eg' : [ 2, -1,  0,  0,  2,  2, -1,  0,  0,  2],
    'T1g': [ 3,  0, -1,  1, -1,  3,  0, -1,  1, -1],
    'T2g': [ 3,  0,  1, -1, -1,  3,  0,  1, -1, -1],
    'A1u': [ 1,  1,  1,  1,  1, -1, -1, -1, -1, -1],
    'A2u': [ 1,  1, -1, -1,  1, -1, -1,  1,  1, -1],
    'Eu' : [ 2, -1,  0,  0,  2, -2,  1,  0,  0, -2],
    'T1u': [ 3,  0, -1,  1, -1, -3,  0,  1, -1,  1],
    'T2u': [ 3,  0,  1, -1, -1, -3,  0, -1,  1,  1],
}

OH_IRREP_DIMS = {
    'A1g': 1, 'A2g': 1, 'Eg': 2, 'T1g': 3, 'T2g': 3,
    'A1u': 1, 'A2u': 1, 'Eu': 2, 'T1u': 3, 'T2u': 3,
}


# ============================================================
# Main analysis
# ============================================================

def main():
    log("=" * 78)
    log("BCC 3x3x3 flat-band (lambda=-3) Oh irrep decomposition")
    log("=" * 78)

    # --------------------------------------------------------
    # Step 1: Build lattice and faces
    # --------------------------------------------------------
    log("\n[Step 1] Build lattice and faces (translation-equivariant basis)")
    body_centers = build_bcc_lattice_periodic()
    face_to_idx, bc_face_indices, ref_faces = build_all_faces(body_centers)

    N = len(face_to_idx)
    log(f"  Total unique faces: {N} (expect 540)")
    assert N == 540

    ref_face_to_local_idx = {face: m for m, face in enumerate(ref_faces)}
    log(f"  Reference BC(0,0,0) faces: {len(ref_faces)} (expect 20)")

    # --------------------------------------------------------
    # Step 2: Build 540x540 adjacency matrix and block-decompose
    # --------------------------------------------------------
    log("\n[Step 2] Build adjacency matrix and extract T(0,0,0) self-block")
    A = build_adjacency_matrix(face_to_idx)
    log(f"  A shape: {A.shape}, symmetric: {np.allclose(A, A.T)}")

    # Reorder into BC-block form
    perm = []
    for bc_idx in range(27):
        perm.extend(bc_face_indices[bc_idx])
    perm = np.array(perm, dtype=int)
    A_reord = A[np.ix_(perm, perm)]

    ref_flat = bc_flat_index((0, 0, 0))  # = 0
    T_self = A_reord[:20, :20].copy()  # T(0,0,0): the self-coupling block

    log(f"  T(0,0,0) shape: {T_self.shape}")
    log(f"  T(0,0,0) symmetric: {np.allclose(T_self, T_self.T)}")
    log(f"  T(0,0,0) nonzero entries: {int(np.count_nonzero(T_self))}")

    # --------------------------------------------------------
    # Step 3: Diagonalize T(0,0,0) and look for eigenvalue -3
    # --------------------------------------------------------
    log("\n[Step 3] Diagonalize T(0,0,0) and search for eigenvalue -3")
    eigvals_T, eigvecs_T = np.linalg.eigh(T_self)

    # Group eigenvalues
    def group_eigs(ev, tol=1e-6):
        groups = []
        cur = [ev[0]]
        for e in ev[1:]:
            if abs(e - cur[-1]) <= tol:
                cur.append(e)
            else:
                groups.append(cur)
                cur = [e]
        groups.append(cur)
        return [(float(np.mean(g)), len(g)) for g in groups]

    grouped_T = group_eigs(np.sort(eigvals_T))
    log(f"  T(0,0,0) eigenvalue spectrum:")
    for lam, deg in grouped_T:
        marker = " <--- TARGET" if abs(lam - (-3.0)) < 1e-4 else ""
        log(f"    lambda = {lam:10.6f}  deg = {deg}{marker}")

    # Check if -3 is an eigenvalue of T(0,0,0)
    T_has_minus3 = any(abs(lam - (-3.0)) < 1e-4 for lam, deg in grouped_T)
    log(f"\n  T(0,0,0) has eigenvalue -3? {T_has_minus3}")

    # Always build T(R) hopping matrices with CENTERED displacements.
    # On a 3-torus, displacement R=(2,0,0) and R=(-1,0,0) are the same.
    # We use centered convention: R in {-1,0,1}^3 (mod 3: {0->0, 1->1, 2->-1}).
    # This ensures H(k) = sum_R exp(ik.R) T(R) with standard Bloch phase convention.
    log("\n  Building T(R) for all 27 displacement vectors R (centered convention)...")
    T_hop = {}  # keys: centered R tuples in {-1,0,1}^3
    for bc_j_idx, bc_j_ijk in enumerate(body_centers):
        # Center the displacement: map {0,1,2} -> {0,1,-1}
        Rc = tuple((r + 1) % 3 - 1 for r in bc_j_ijk)
        T_hop[Rc] = A_reord[:20, bc_j_idx*20:(bc_j_idx+1)*20].copy()
    log(f"  T(R) matrices built: {len(T_hop)} distinct R vectors (centered)")
    nonzero_Rs = [R for R, T in T_hop.items() if np.linalg.norm(T, 'fro') > 1e-10]
    log(f"  Non-zero T(R) at R: {sorted(nonzero_Rs)}")

    if T_has_minus3:
        # Get eigenvectors at -3
        minus3_mask = np.abs(eigvals_T - (-3.0)) < 1e-4
        n_minus3 = np.sum(minus3_mask)
        log(f"  Multiplicity of -3 in T(0,0,0): {n_minus3}")
        V = eigvecs_T[:, minus3_mask]  # 20 x n_minus3
        source = "T(0,0,0)"
    else:
        log("\n  T(0,0,0) does NOT have eigenvalue -3.")
        log("  Building H(k=0) = sum_R T(R) and extracting its -3 eigenspace.")
        log("  Physical note: The flat-band eigenvectors at different k are related")
        log("  by the Bloch factor, so the k=0 sector gives the irrep content.")
        log("  The Oh group is a symmetry of H(k=0) since it fixes k=0.")

        # Build H(k=0) with centered R
        H_gamma = np.zeros((20, 20), dtype=float)
        for Rc, T_R in T_hop.items():
            H_gamma += T_R  # exp(ik.R) = 1 at k=0

        log(f"  H(k=0) = sum_R T(R), shape {H_gamma.shape}")
        log(f"  H(k=0) symmetric: {np.allclose(H_gamma, H_gamma.T)}")

        eigvals_H, eigvecs_H = np.linalg.eigh(H_gamma)
        grouped_H = group_eigs(np.sort(eigvals_H))
        log(f"  H(k=0) eigenvalue spectrum:")
        for lam, deg in grouped_H:
            marker = " <--- TARGET" if abs(lam - (-3.0)) < 1e-4 else ""
            log(f"    lambda = {lam:10.6f}  deg = {deg}{marker}")

        H_has_minus3 = any(abs(lam - (-3.0)) < 1e-4 for lam, deg in grouped_H)
        if not H_has_minus3:
            log("\n  ERROR: H(k=0) also does not have eigenvalue -3!")
            log("  Something is wrong with the lattice construction.")
            sys.exit(1)

        minus3_mask_H = np.abs(eigvals_H - (-3.0)) < 1e-4
        n_minus3 = int(np.sum(minus3_mask_H))
        log(f"  Multiplicity of -3 in H(k=0): {n_minus3}")
        V = eigvecs_H[:, minus3_mask_H]
        source = "H(k=0)"

        # Verify H(k=0) V = -3 V
        HV_err = np.max(np.abs(H_gamma @ V - (-3.0) * V))
        log(f"  Verify H(k=0) V = -3 V: max err = {HV_err:.2e}")

        # Also check H(k) at other k-points — the 6D space rotates with k
        log(f"\n  Checking -3 eigenvalue exists at all 27 k-points:")
        all_have_minus3 = True
        for n1, n2, n3 in itertools.product(range(3), repeat=3):
            k = np.array([2*np.pi/3 * n1, 2*np.pi/3 * n2, 2*np.pi/3 * n3])
            H_k = np.zeros((20, 20), dtype=complex)
            for Rc, T_R in T_hop.items():
                phase = np.exp(1j * (k[0]*Rc[0] + k[1]*Rc[1] + k[2]*Rc[2]))
                H_k += phase * T_R
            ev_k = np.sort(np.real(np.linalg.eigvalsh(H_k)))
            has_minus3 = np.abs(ev_k[0] - (-3.0)) < 1e-4
            if not has_minus3:
                all_have_minus3 = False
                log(f"  WARNING: k=({n1},{n2},{n3}) does NOT have -3 eigenvalue!")
        log(f"  All 27 k-points have -3 eigenvalue: {all_have_minus3}")

    log(f"\n  Using 6D flat-band eigenspace from {source}")
    log(f"  V shape: {V.shape} (should be 20 x 6)")

    if V.shape[1] != 6:
        log(f"  WARNING: expected 6 eigenvectors, got {V.shape[1]}. Proceeding anyway.")

    # Verify orthonormality
    VTV = V.T @ V
    orth_err = np.max(np.abs(VTV - np.eye(V.shape[1])))
    log(f"  V^T V orthonormality error: {orth_err:.3e}")

    # --------------------------------------------------------
    # Step 4: Verify flat-band modes are null vectors of T(R!=0)
    # --------------------------------------------------------
    log("\n[Step 4] Verify Oh symmetry of H(k=0) restricted to flat-band space")
    log("  (Checking P(g) commutes with H(k=0) restricted to V)")

    # Verify that H(k=0) V = -3 V
    H_gamma_check = np.zeros((20, 20), dtype=float)
    for Rc, T_R in T_hop.items():
        H_gamma_check += T_R
    HV_err_check = np.max(np.abs(H_gamma_check @ V - (-3.0) * V))
    log(f"  H(k=0) V = -3 V: max err = {HV_err_check:.2e}  OK={HV_err_check < 1e-8}")

    # Note about flat bands: The H(k) at each k-point has -3 as eigenvalue,
    # but the 6D eigenspace ROTATES with k (not a fixed subspace of R^20).
    # The k=0 sector gives the local Oh representation correctly because:
    # Oh fixes k=0 (since Oh is the little group of k=0), so P(g) commutes with H(k=0).
    log("  (T(R)V != 0 in general for non-null flat bands -- this is expected)")
    log("  (What matters: H(k=0) is Oh-invariant, and V spans its -3 eigenspace)")

    # --------------------------------------------------------
    # Step 5: Generate Oh and verify classification
    # --------------------------------------------------------
    log("\n[Step 5] Generate Oh group (48 elements) and classify")
    oh_elements = generate_oh_elements()
    log(f"  Generated {len(oh_elements)} Oh elements")
    oh_classes, class_ok = verify_oh_classification(oh_elements)

    # Also classify each element individually for later use
    element_class = [classify_oh_element(g) for g in oh_elements]

    # --------------------------------------------------------
    # Step 6: Build 20x20 permutation matrices and project to 6D
    # --------------------------------------------------------
    log("\n[Step 6] Build Oh permutation matrices on 20-face basis and project to 6D")

    # Verify the Oh action on reference faces is well-defined
    # (i.e., the geometric action maps each BC(0,0,0) face to some BC face, and
    #  after translation back, lands in the reference set)
    log("  Testing Oh action on reference faces...")

    n_bad = 0
    for g_idx, g in enumerate(oh_elements):
        try:
            P = build_oh_permutation(g, ref_faces, ref_face_to_local_idx,
                                     face_to_idx, bc_face_indices, body_centers)
        except Exception as e:
            log(f"  ERROR for element {g_idx}: {e}")
            n_bad += 1
            if n_bad > 3:
                log("  Too many errors, aborting.")
                sys.exit(1)

    log(f"  All 48 permutation matrices well-defined: {n_bad == 0}")

    # Now build all 48 permutation matrices and the 6x6 representation matrices
    rep_matrices = []
    chars = []
    perm_chars = []

    log("  Building 48 representation matrices R(g) = V^T P(g) V ...")
    for g in oh_elements:
        P = build_oh_permutation(g, ref_faces, ref_face_to_local_idx,
                                 face_to_idx, bc_face_indices, body_centers)
        R_g = V.T @ P @ V  # 6x6
        rep_matrices.append(R_g)
        chars.append(float(np.trace(R_g)))
        perm_chars.append(float(np.trace(P)))

    # Verify group homomorphism: R(g*h) = R(g)*R(h) for a sample
    log("  Verifying group homomorphism R(g*h) = R(g)*R(h) ...")
    max_hom_err = 0.0
    # Check all pairs (expensive: 48*48=2304, but manageable)
    for i, gi in enumerate(oh_elements):
        for j, gj in enumerate(oh_elements):
            gh = gi @ gj
            # Find index of gh in oh_elements
            gh_key = tuple(gh.flatten())
            gh_idx = None
            for k, gk in enumerate(oh_elements):
                if np.array_equal(gk, gh):
                    gh_idx = k
                    break
            if gh_idx is None:
                log(f"  ERROR: product g[{i}]*g[{j}] not found in Oh!")
                continue
            err = np.max(np.abs(rep_matrices[i] @ rep_matrices[j] - rep_matrices[gh_idx]))
            if err > max_hom_err:
                max_hom_err = err

    log(f"  Max |R(g)*R(h) - R(g*h)|: {max_hom_err:.3e}")
    log(f"  Valid group representation: {max_hom_err < 1e-8}")

    # Verify R(g) is orthogonal
    max_orth_err = 0.0
    for R_g in rep_matrices:
        err = np.max(np.abs(R_g.T @ R_g - np.eye(6)))
        if err > max_orth_err:
            max_orth_err = err
    log(f"  Max |R(g)^T R(g) - I|: {max_orth_err:.3e}")
    log(f"  All R(g) orthogonal: {max_orth_err < 1e-8}")

    # --------------------------------------------------------
    # Step 7: Characters by conjugacy class
    # --------------------------------------------------------
    log("\n[Step 7] Characters of the 6D representation by conjugacy class")

    # Compute mean character per class
    class_chars = {}
    class_perm_chars = {}
    for cls in OH_CLASSES:
        elem_indices = [i for i, c in enumerate(element_class) if c == cls]
        if not elem_indices:
            class_chars[cls] = 0.0
            class_perm_chars[cls] = 0.0
            continue
        chi_vals = [chars[i] for i in elem_indices]
        pchi_vals = [perm_chars[i] for i in elem_indices]
        # All should be equal within a conjugacy class
        chi_mean = float(np.mean(chi_vals))
        chi_spread = float(np.max(np.abs(np.array(chi_vals) - chi_mean)))
        class_chars[cls] = chi_mean
        class_perm_chars[cls] = float(np.mean(pchi_vals))
        if chi_spread > 1e-6:
            log(f"  WARNING: characters not constant within class {cls}, spread={chi_spread:.3e}")

    log(f"\n  {'Class':10s} | {'Size':4s} | {'chi(P, 20D)':11s} | {'chi(R, 6D)':10s}")
    log(f"  {'-'*10}-+-{'-'*4}-+-{'-'*11}-+-{'-'*10}")
    for cls in OH_CLASSES:
        sz = OH_CLASS_ORDER[cls]
        chi_P = class_perm_chars[cls]
        chi_R = class_chars[cls]
        log(f"  {cls:10s} | {sz:4d} | {chi_P:11.4f} | {chi_R:10.4f}")

    # --------------------------------------------------------
    # Step 8: Decompose into Oh irreps
    # --------------------------------------------------------
    log("\n[Step 8] Decompose 6D representation into Oh irreducible representations")
    log("  Using n_mu = (1/48) sum_g chi_mu(g)* chi(g)")
    log("        = (1/48) sum_cls |cls| * chi_mu(cls)* chi(cls)")

    irrep_multiplicities = {}
    for irrep, char_row in OH_CHAR_TABLE.items():
        n_mu = 0.0
        for cls_idx, cls in enumerate(OH_CLASSES):
            sz = OH_CLASS_ORDER[cls]
            chi_mu = char_row[cls_idx]
            chi_our = class_chars[cls]
            n_mu += sz * chi_mu * chi_our
        n_mu /= 48.0
        irrep_multiplicities[irrep] = n_mu

    log(f"\n  {'Irrep':6s} | {'dim':3s} | {'n_mu (raw)':12s} | {'n_mu (rounded)':14s} | {'contribution'}")
    log(f"  {'-'*6}-+-{'-'*3}-+-{'-'*12}-+-{'-'*14}-+-{'-'*12}")

    total_dim_check = 0
    decomp_str_parts = []
    for irrep in ['A1g', 'A2g', 'Eg', 'T1g', 'T2g', 'A1u', 'A2u', 'Eu', 'T1u', 'T2u']:
        n_raw = irrep_multiplicities[irrep]
        n_round = int(round(n_raw))
        dim = OH_IRREP_DIMS[irrep]
        contrib = n_round * dim
        total_dim_check += contrib
        dev = abs(n_raw - n_round)
        marker = " <--" if n_round > 0 else ""
        log(f"  {irrep:6s} | {dim:3d} | {n_raw:12.6f} | {n_round:14d} | {contrib:3d}{marker}")
        if n_round > 0:
            if n_round == 1:
                decomp_str_parts.append(irrep)
            else:
                decomp_str_parts.append(f"{n_round}x{irrep}")

    decomp_str = " + ".join(decomp_str_parts) if decomp_str_parts else "(none)"
    log(f"\n  Total dimension check: {total_dim_check} (expect 6)")
    log(f"  Decomposition: 6D = {decomp_str}")

    # --------------------------------------------------------
    # Step 9: Interpretation
    # --------------------------------------------------------
    log("\n[Step 9] Physical interpretation")

    # Check specific hypotheses
    t1u_count = int(round(irrep_multiplicities['T1u']))
    t2u_count = int(round(irrep_multiplicities['T2u']))
    t1g_count = int(round(irrep_multiplicities['T1g']))
    t2g_count = int(round(irrep_multiplicities['T2g']))
    eg_count  = int(round(irrep_multiplicities['Eg']))

    log(f"\n  Testing hypotheses:")
    log(f"  H1: 2xT1u (two copies of vector rep, like +/-x,+/-y,+/-z faces)")
    log(f"      T1u multiplicity = {t1u_count}  -> {'YES' if t1u_count == 2 else 'NO'}")
    log(f"  H2: T1g + T2g")
    log(f"      T1g={t1g_count}, T2g={t2g_count}  -> {'YES' if t1g_count==1 and t2g_count==1 else 'NO'}")
    log(f"  H3: Eg + T1u (2+3=5, dimension mismatch for 6D -> unlikely)")
    log(f"      Eg={eg_count}, T1u={t1u_count}  -> {'YES' if eg_count==1 and t1u_count==1 else 'NO'}")
    log(f"  H4: T1u + T2u")
    log(f"      T1u={t1u_count}, T2u={t2u_count}  -> {'YES' if t1u_count==1 and t2u_count==1 else 'NO'}")

    log(f"\n  Actual decomposition: {decomp_str}")

    # Physical context:
    log(f"\n  Physical context:")
    log(f"  The 6 flat-band modes at lambda=-3 span 3D face-orientation space.")
    log(f"  T1u (dim 3) = vector representation (odd under inversion) ~ x,y,z polarizations.")
    log(f"  T2u (dim 3) = pseudovector under inversion, transforms as xy,yz,xz.")
    log(f"  T1g (dim 3) = axial vector (even under inversion).")
    log(f"  T2g (dim 3) = even parity, transforms as xy,yz,xz.")
    log(f"  2xT1u would mean the 6 modes are two copies of {{+-x,+-y,+-z}} face-pointing modes.")

    # --------------------------------------------------------
    # Step 10: Consistency checks
    # --------------------------------------------------------
    log("\n[Step 10] Consistency checks")

    # Check: sum of |cls|*chi(cls)^2 / 48 = sum of n_mu^2 (only if irreducible)
    reg_sum = sum(OH_CLASS_ORDER[cls] * class_chars[cls]**2 for cls in OH_CLASSES) / 48
    log(f"  sum |cls|*chi^2 / 48 = {reg_sum:.4f}  (= sum n_mu^2 = {sum(int(round(v))**2 for v in irrep_multiplicities.values())})")
    log(f"  -> Representation is reducible (expect sum > 1 for reducible)")

    # Check: all n_mu are integers
    all_int = all(abs(v - round(v)) < 1e-4 for v in irrep_multiplicities.values())
    log(f"  All multiplicities are integers: {all_int}")

    # Verify character values are self-consistent
    log(f"\n  Character verification: recompute chi from decomposition")
    log(f"  chi(cls) = sum_irrep n_mu * chi_mu(cls)")
    log(f"\n  {'Class':10s} | {'Computed':10s} | {'From P proj':12s} | {'Match?'}")
    log(f"  {'-'*10}-+-{'-'*10}-+-{'-'*12}-+-{'-'*6}")
    max_char_err = 0.0
    for cls_idx, cls in enumerate(OH_CLASSES):
        chi_recomp = sum(
            int(round(irrep_multiplicities[irrep])) * OH_CHAR_TABLE[irrep][cls_idx]
            for irrep in OH_CHAR_TABLE
        )
        chi_actual = class_chars[cls]
        err = abs(chi_recomp - chi_actual)
        max_char_err = max(max_char_err, err)
        log(f"  {cls:10s} | {chi_recomp:10.4f} | {chi_actual:12.4f} | {err < 1e-4}")

    log(f"  Max character reconstruction error: {max_char_err:.3e}")

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------
    log("\n" + "=" * 78)
    log("SUMMARY")
    log("=" * 78)
    log(f"\n  Lattice: BCC 3x3x3 periodic (3-torus), 540 faces, 27 BCs x 20 faces")
    log(f"  Flat bands: 6 bands all pinned at lambda=-3 for ALL 27 k-points")
    log(f"  Flat-band eigenspace source: {source} (20x6 matrix V)")
    log(f"  Oh action: 48 elements acting on 20-face basis of reference BC(0,0,0)")
    log(f"  Group homomorphism error: {max_hom_err:.3e}")
    log(f"  Orthogonality error:      {max_orth_err:.3e}")
    log(f"\n  6D representation characters by class:")
    for cls in OH_CLASSES:
        log(f"    {cls:10s}: {class_chars[cls]:.4f}")
    log(f"\n  Irrep decomposition:")
    for irrep in ['A1g', 'A2g', 'Eg', 'T1g', 'T2g', 'A1u', 'A2u', 'Eu', 'T1u', 'T2u']:
        n = int(round(irrep_multiplicities[irrep]))
        if n > 0:
            log(f"    {n} x {irrep} (dim {OH_IRREP_DIMS[irrep]})")
    log(f"\n  6D = {decomp_str}")
    log(f"\n  Hypothesis 2xT1u (two copies of vector representation): "
        f"{'CONFIRMED' if t1u_count == 2 and sum(int(round(v)) for v in irrep_multiplicities.values()) == 2 else 'NOT CONFIRMED'}")
    log(f"\n=== DONE ===")


if __name__ == "__main__":
    try:
        main()
    finally:
        try:
            with open(OUT_PATH, "w", encoding="utf-8") as f:
                f.write("\n".join(_LOG_LINES) + "\n")
            print(f"\n[results written to {OUT_PATH}]")
        except Exception as e:
            print(f"WARNING: failed to write results file: {e}", file=sys.stderr)
